export const cardsArr = [
  {
    id: 4,
    display_title: "TOOTHPASTE BITS FLUORIDE-FREE",
    src: "/products/1/pc-tpb-ff-4oz-mint-no-bg.webp",
    colors: [
      { colorId: 0, color: "#c7f6e6", clicked: true },
      { colorId: 1, color: "#4d4c4c", clicked: false },
      { colorId: 2, color: "#ffbdb9", clicked: false },
    ],
    type: "Mint",
    reviews: "21,266",
    month_price: 8,

    title: "Toothpaste Bits",
    fluoride: false,
    count: 1,
    price: 32,
    old_price: 48,
  },
  {
    id: 5,
    display_title: "TOOTHPASTE BITS WITH FLUORIDE",
    src: "/products/2/pc-tpb-wf-2oz-mint-fluoride-no-bg.webp",
    colors: [{ colorId: 0, color: "#c7f6e6", clicked: true }],
    type: "Mint",
    reviews: "21,266",
    month_price: 8,

    title: "Toothpaste Bits",
    fluoride: true,
    count: 1,
    price: 32,
    old_price: 48,
  },
  {
    id: 6,
    display_title: "DEODORANT SET",
    src: "/products/3/pdp-product-card-desktop-silver-case-open-no-bg.webp",
    colors: [
      { colorId: 0, color: "#f0f0f0", clicked: true },
      { colorId: 1, color: "#f27c2d", clicked: false },
      { colorId: 2, color: "#e5497a", clicked: false },
      { colorId: 3, color: "#51511a", clicked: false },
    ],
    type: "Fragrance-Free",
    reviews: "644",
    month_price: 8,

    title: "Deodorant set",
    count: 1,
    price: 32,
    old_price: 0,
  },
  {
    id: 7,
    display_title: "MOUTHWASH BITS",
    src: "/products/4/pc-mouthwash-no-bg.webp",
    colors: [{ colorId: 0, color: "#c7f6e6", clicked: true }],
    type: "Mint",
    reviews: "834",
    month_price: 5,

    title: "Mouthwash Bits",
    description: "Mouthwash",
    count: 1,
    price: 20,
    old_price: 0,
  },
];
